#!/bin/bash
#PBS -P y99
#PBS -q express
#PBS -l walltime=00:10:00,software=intel-fc,ncpus=608,mem=608gb
#PBS -j oe

module load intel-fc
module load intel-cc
module load netcdf
module load openmpi/1.10.2

if [ -e /short/m68/kaa561/metroms_iceshelf/tmproms/run/circumpolar/oceanM ]; then
    rm /short/m68/kaa561/metroms_iceshelf/tmproms/run/circumpolar/oceanM
    rm /short/m68/kaa561/metroms_iceshelf/tmproms/run/circumpolar/cice/rundir/compile/libcice.a
fi

cd $PBS_O_WORKDIR
cd ..
source myenv.bash
if [ ! -d /short/m68/kaa561/metroms_iceshelf/tmproms/MCT ]; then
    ./build_mct.sh
fi
./build_cice.sh circumpolar 96 1  
./build_roms.sh circumpolar -j 608
cd $PBS_O_WORKDIR
if [ -e /short/m68/kaa561/metroms_iceshelf/tmproms/run/circumpolar/oceanM ]; then 
   echo "Success"
    qsub roms.job
    #qsub -v NJOBS=4 roms_rep.job
else
    echo "Problem with compilation"
fi
   
